from typing import Dict, Any

_JAVA_TYPES = {
    "String": {"type": "string"},
    "Integer": {"type": "integer"}, "int": {"type": "integer"},
    "Long": {"type": "integer", "format": "int64"}, "long": {"type": "integer", "format": "int64"},
    "Double": {"type": "number", "format": "double"}, "double": {"type": "number"},
    "Float": {"type": "number", "format": "float"}, "float": {"type": "number"},
    "Boolean": {"type": "boolean"}, "boolean": {"type": "boolean"},
    "List": {"type": "array", "items": {"type": "object"}},
}

_STATUS = {
    "GET": {"200": {"description": "Success"}},
    "POST": {"201": {"description": "Created"}, "400": {"description": "Bad Request"}},
    "PUT": {"200": {"description": "Updated"}, "404": {"description": "Not Found"}},
    "DELETE": {"204": {"description": "No Content"}, "404": {"description": "Not Found"}},
    "PATCH": {"200": {"description": "Updated"}, "404": {"description": "Not Found"}},
}


def _oa_type(java_type: str) -> dict:
    return _JAVA_TYPES.get(java_type, {"type": "string"})


def build_openapi(project_name: str, parsed: Dict[str, Any]) -> dict:
    schemas = {}
    for dto in parsed["dtos"]:
        props = {f["name"]: _oa_type(f.get("type", "String")) for f in dto["fields"]}
        schemas[dto["name"]] = {"type": "object", "properties": props}

    paths: dict = {}
    for ep in parsed["endpoints"]:
        path_key = ep["path"]
        method_key = ep["http_method"].lower()

        path_params = [
            {"name": p["name"], "in": p["param_type"], "required": p["required"], "schema": _oa_type(p.get("data_type") or "String")}
            for p in ep["parameters"] if p["param_type"] in ("path", "query", "header")
        ]
        body_params = [p for p in ep["parameters"] if p["param_type"] == "body"]

        operation: dict = {
            "summary": f"{ep['http_method']} {ep['path']}",
            "operationId": f"{method_key}_{ep['method_name'] or path_key.replace('/', '_').strip('_')}",
            "tags": [ep["controller_name"] or "default"],
            "parameters": path_params,
            "responses": _STATUS.get(ep["http_method"], {"200": {"description": "Success"}}),
        }

        if ep["auth_required"]:
            operation["security"] = [{"bearerAuth": []}]

        if body_params and ep["http_method"] in ("POST", "PUT", "PATCH"):
            dto_name = body_params[0].get("data_type")
            schema_ref = {"$ref": f"#/components/schemas/{dto_name}"} if dto_name and dto_name in schemas else {"type": "object"}
            operation["requestBody"] = {"required": True, "content": {"application/json": {"schema": schema_ref}}}

        paths.setdefault(path_key, {})[method_key] = operation

    return {
        "openapi": "3.0.3",
        "info": {"title": project_name, "description": "Auto-generated by API Documentation AI CLI", "version": "1.0.0"},
        "paths": paths,
        "components": {
            "schemas": schemas,
            "securitySchemes": {"bearerAuth": {"type": "http", "scheme": "bearer", "bearerFormat": "JWT"}},
        },
    }
