from typing import List
from app.models.endpoint import Endpoint
from app.models.dto import DTO, Parameter
from sqlalchemy.orm import Session


def _method_to_status(method: str) -> dict:
    return {
        "GET": {"200": {"description": "Success"}},
        "POST": {"201": {"description": "Created"}, "400": {"description": "Bad Request"}},
        "PUT": {"200": {"description": "Updated"}, "404": {"description": "Not Found"}},
        "DELETE": {"204": {"description": "No Content"}, "404": {"description": "Not Found"}},
        "PATCH": {"200": {"description": "Updated"}, "404": {"description": "Not Found"}},
    }.get(method, {"200": {"description": "Success"}})


def _java_type_to_openapi(java_type: str) -> dict:
    mapping = {
        "String": {"type": "string"},
        "Integer": {"type": "integer"}, "int": {"type": "integer"},
        "Long": {"type": "integer", "format": "int64"}, "long": {"type": "integer", "format": "int64"},
        "Double": {"type": "number", "format": "double"}, "double": {"type": "number"},
        "Float": {"type": "number", "format": "float"}, "float": {"type": "number"},
        "Boolean": {"type": "boolean"}, "boolean": {"type": "boolean"},
        "List": {"type": "array", "items": {"type": "object"}},
    }
    return mapping.get(java_type, {"type": "string"})


def _build_dto_schema(dto: DTO) -> dict:
    properties = {}
    required = []
    if dto.fields:
        for field in dto.fields:
            properties[field["name"]] = _java_type_to_openapi(field.get("type", "String"))
            if field.get("required"):
                required.append(field["name"])
    schema = {"type": "object", "properties": properties}
    if required:
        schema["required"] = required
    return schema


def generate_openapi(project_name: str, project_id: str, db: Session) -> dict:
    endpoints: List[Endpoint] = db.query(Endpoint).filter(Endpoint.project_id == project_id).all()
    dtos: List[DTO] = db.query(DTO).filter(DTO.project_id == project_id).all()

    # Build component schemas from DTOs
    schemas = {}
    for dto in dtos:
        schemas[dto.name] = _build_dto_schema(dto)

    # Build paths
    paths = {}
    for ep in endpoints:
        params = db.query(Parameter).filter(Parameter.endpoint_id == ep.id).all()
        path_key = ep.path

        path_params = [
            {
                "name": p.name,
                "in": p.param_type,
                "required": p.required,
                "schema": _java_type_to_openapi(p.data_type or "String"),
            }
            for p in params if p.param_type in ("path", "query", "header")
        ]

        body_params = [p for p in params if p.param_type == "body"]

        operation: dict = {
            "summary": ep.description or f"{ep.http_method} {ep.path}",
            "operationId": f"{ep.http_method.lower()}_{ep.method_name or ep.path.replace('/', '_').strip('_')}",
            "tags": [ep.controller_name or "default"],
            "parameters": path_params,
            "responses": _method_to_status(ep.http_method),
        }

        if ep.auth_required:
            operation["security"] = [{"bearerAuth": []}]

        if body_params and ep.http_method in ("POST", "PUT", "PATCH"):
            body_param = body_params[0]
            dto_name = body_param.data_type
            if dto_name and dto_name in schemas:
                operation["requestBody"] = {
                    "required": True,
                    "content": {"application/json": {"schema": {"$ref": f"#/components/schemas/{dto_name}"}}}
                }
            else:
                operation["requestBody"] = {
                    "required": True,
                    "content": {"application/json": {"schema": {"type": "object"}}}
                }

        method_key = ep.http_method.lower()
        if path_key not in paths:
            paths[path_key] = {}
        paths[path_key][method_key] = operation

    spec = {
        "openapi": "3.0.3",
        "info": {
            "title": project_name,
            "description": f"Auto-generated by API Documentation AI",
            "version": "1.0.0",
        },
        "paths": paths,
        "components": {
            "schemas": schemas,
            "securitySchemes": {
                "bearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                    "bearerFormat": "JWT",
                }
            },
        },
    }

    return spec
